apiVersion: v1
kind: Service
metadata:
  name: tracks
  annotations:
    tailscale.com/hostname: tracks
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: dawarich
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: dawarich