---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tenant-login
  namespace: backups
spec:
  encryptedData:
    config.env: AgBMBjj/nTVsZM2lbL1hNoKpk+dHx5FhHNSiK1JysKslvLhffBfPzHzyG2Xhv/xvS+y86vSVihY8XwafaeDB1vEpgI2XvA9Uk8l1zXU6FY8+3SVVR93ldD2YGjEBpgfkENrWg8x6F8XG5+4oqDVWv3h+vVyuVq4FmKHLzHYjrp0+hxPwelPg1yMVT2mR51X9UzBRLTV/Pqbi1h1G1VZB0V1y7je05xaWpof+l6GKO8Y1ppKfag7zfxSNshy+OHQihjMtzV7o1mF1Iz+/rAB2jeFsvcjbkoRAeVgKR/jAaHuUe86vL4zvSeI299e69rotsyo5vKsGw+m81ZtSpWCn279Lb4ChnvoKQr4m+VPCbupbm1gksA+BNv46ndOfEj2cS7ateplqkqFe93WBrzA7o5jJBmSmBqQz6fkloAhqL7l8aVtW3HhePR6sHUyieh1GA9mt5oviLAntlGKr8g6d16Lzl4o1Lx0XrcqzUknJx8VkiR9BevpVg/RaSKvaj1Q4zlD8zFfFigw36RRoMDivLrhvFOh+VrBraecb133WDTrTK/WuIL89qM9ugHfDNV5/lf+RVcaXcePwMm+dutmWCruDA4iEituP1v/cP8F1X83sFj07BopNMsqFl9WeoSLLzdrSBVDhUXjOnsrpiaHoconHoa8Z+aHRpHe72sGYQDRZOINH2RNVrbcGHzyEUPpiM5A8+tQ5p8mbp658RwWYJYq29UNVfSFETQJjmlnC/oSICRzq15hWhk9rRX7kjYbSV/gBysr6pe6o0aGM2gz32KWiWFLNHV8/8Ox9FMchrLI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tenant-login
      namespace: backups
    type: Opaque
