apiVersion: v1
kind: Service
metadata:
  name: ultron
  namespace: backups
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: minio
    port: 9000
    protocol: TCP
    targetPort: minio
  - name: eternal-console
    port: 9443
    protocol: TCP
    targetPort: eternal-console
  selector:
    app: minio
    app.kubernetes.io/instance: tenant
