home-assistant:
  image:
    # -- image repository
    repository: ghcr.io/home-assistant/home-assistant
    # -- image tag
    # @default -- chart.appVersion
    tag: "2024.3.3"
    # -- image pull policy
    pullPolicy: IfNotPresent
  
  # -- environment variables.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: "America/Chicago"
  
  # -- Configures service settings for the chart. Normally this does not need to be modified.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 8123
  
  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: tailscale
      hosts:
      - host: maria-hill
        paths:
          - path: /
      defaultBackend:
        service:
          name: home-assistant
          port:
            number: 8123
      tls:
      - hosts:
        - maria-hill
  
  # -- Enable devices to be discoverable
  hostNetwork: true
  
  # -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
  dnsPolicy: ClusterFirstWithHostNet
  
  securityContext:
    # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
    privileged: true
  
  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      retain: true
      accessMode: ReadWriteOnce
      size: 20Gi
    # -- Configure a hostPathMount to mount a USB device in the container.
    # @default -- See values.yaml
  usb:
    enabled: false
    # type: hostPath
    # hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE3018882-if00
  
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #           - zigbee-controller
  
  # -- Enable and configure postgresql database subchart under this key.
  #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
  # @default -- See values.yaml
  postgresql:
    enabled: true
    image:
      repository: bitnami/postgresql
      tag: 15.5.0
    auth:
      username: home-assistant
      password: "oracle-deserves-destruction"
      database: home-assistant
    persistence:
      primary:
        enabled: true
        # storageClass: ""
  
  metrics:
    # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
    # @default -- See values.yaml
    enabled: true
    serviceMonitor:
      interval: 1m
      scrapeTimeout: 30s
      labels: {}
      ## See https://www.home-assistant.io/docs/authentication/ for where to find
      ## long lived access token creation under your account profile, which is
      ## needed to monitor Home Assistant
      # bearerTokenSecret:
      #   name: ""
      #   key: ""
  
    # -- Enable and configure Prometheus Rules for the chart under this key.
    # @default -- See values.yaml
    prometheusRule:
      enabled: false
      labels: {}
      # -- Configure additionial rules for the chart under this key.
      # @default -- See prometheusrules.yaml
      rules: []
        # - alert: HomeAssistantAbsent
        #   annotations:
        #     description: Home Assistant has disappeared from Prometheus service discovery.
        #     summary: Home Assistant is down.
        #   expr: |
        #     absent(up{job=~".*home-assistant.*"} == 1)
        #   for: 5m
        #   labels:
        #     severity: critical
  
addons:
  codeserver:
    # -- Enable VS Code server addon.
    #    This allows for easy access to configuration.yaml
    enabled: false
    # -- Enable and configure ingress settings for the VS Code server under this key.
    # @default -- See [values.yaml](./values.yaml)
    ingress:
      enabled: false
      # hosts:
      #   - host: code.example.com
      #     paths:
      #       - path: /
      # tls:
      #   - secretName: code.example.com-tls
      #     hosts:
      #       - code.example.com
    # @ignored
    args:
      - --auth=none
      - --user-data-dir=/data/config/.vscode
    # @ignored
    volumeMounts:
      - name: config
        mountPath: /data/config
