apiVersion: v1
kind: Service
metadata:
  name: hoard
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: hoard
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: karakeep-web
  ports:
  - name: http
    port: 80
    targetPort: 3000
