ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
    # -- This configuration defines if Ingress Controller should allow users to set
    # their own *-snippet annotations, otherwise this is forbidden / dropped
    # when users add those annotations.
    # Global snippets in ConfigMap are still respected
    allowSnippetAnnotations: true
