apiVersion: v1
kind: PersistentVolume
metadata:
  name: benoit-pv
spec:
  storageClassName: "nfs"
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.77
    path: /whatever/jellyfin
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benoit-pvc
  namespace: eternal-library
spec:
  storageClassName: "nfs"
  volumeName: benoit-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi