# Default values for PhotoPrism Helm chart

image:
  repository: photoprism/photoprism
  # TODO: Update this to a more recent tag once it's running successfully
  tag: "20211215"
  pullPolicy: IfNotPresent

nameOverride: "Insight"
fullnameOverride: "ProjectInsight"

# Defaults to 'photoprism'
#adminPassword: ""
# Use existing secret for Admin password, key 'PHOTOPRISM_ADMIN_PASSWORD'
existingSecret: project-insight-secret

# Available properties can be discovered by running the command:
#   photoprism config
# The sample docker-compose.yml file in the PhotoPrism git repo
#  is also a good place to look:
# https://github.com/photoprism/photoprism/blob/develop/docker-compose.yml
config:
  PHOTOPRISM_DEBUG: true
  PHOTOPRISM_PUBLIC: false
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_CAPTION: "Project Insight"
  PHOTOPRISM_SITE_DESCRIPTION: "We take the world as it is, not as we'd like it to be"
  PHOTOPRISM_SITE_AUTHOR: "@project-insight"

# nodeSelector:
#   kubernetes.io/hostname:

# sidecarContainers:
#   - name: sidecar
#     image: alpine

persistence:
  enabled: true
  storagePath:   &storagePath    /photoprism/storage
  originalsPath: &originalsPath /photoprism/originals

    # volumeMounts:
    # - name: originals
    #   mountPath: *originalsPath
    #   subPath: photos/family
    # - name: storage
    #   mountPath: *storagePath

    # volumes:
    # - name: originals
    #   nfs:
    #     server: my.nas.hostname
    #     path: /media
    # - name: storage
    #   nfs:
    #     server: my.nas.hostname
    #     path: /photoprism

  volumeClaimTemplates:
  - metadata:
      name: photoprism
    spec:
      accessModes: [ "ReadWriteMany" ]
      # storageClassName: "my-storage-class"   # You'll probably want to ensure your storage class has `reclaimPolicy: Retain`
      resources:
        requests:
          storage: 50Gi


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: project-insight.maximstroud.de
    paths:
    - /
  tls:
  - hosts:
    - project-insight.maximstroud.de
    secretName: maximstroud.de-cert

# securityContext:
#   fsGroup: 100
#   runAsUser: 1000
#   runAsGroup: 1000

resources:
  requests:
    memory: 6Gi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi


# tolerations: []

# affinity: {}


# To use a remote MySQL instance, set the value for driver to 'mysql'
database:
  driver: sqlite
# Set these values only if the mysql driver is used
  # name: photoprism
  # user: photoprism
  # password: photoprism
  # port: 3306
  # host: mariadb.db-mariadb
# Ignore above settings and use existing secret for database DSN. Key 'PHOTOPRISM_DATABASE_DSN'
  # existingSecret:
