apiVersion: v1
kind: Service
metadata:
  name: banner
  namespace: eternal-library
  annotations:
    tailscale.com/hostname: banner
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: eternal-library
