---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC4OBSmq2KQqtBJbTWLQ0KUyYqWau6b7xHSkJvQydbjm5C7GaSlWcpOP9w3axrRqeM/b1Zhe1xXUgky481254dr9uKOHJe+TAzrvpXaEc6GMeM3gKcS7WnLbZ6eJVP0q4ajVbZZZ6PEMDVWK/DYPmrVPhLNs8I/bvxEW6NlZ6IAzYdMY4WiZGHJoWyuFpxmJtWv4hxhSHHPp5bJVIjWfKOL7Z4y9WV7UMPgdKyXhdv+VJ0QFgYJhU1b/EK0EhbnasgbW+y/EuNff/tmNg6LqeSKURa0eoOrrswh4YfA0/tIGQstFJ38ewzGU8Xb7kVurXdjuwIV8bxrdKLzShhaszNVnfiWaYq+bPFWN2oFBM06Y5D+ZoX5XVCSieAPLsmmAOacMZxi8o17oueGX7ONEuMW8vFFVIS61uxErs31HVQxZ3NBZ3sCfXGrK4IFkTyKBhBM/zxmS7kRcid2AmuaneZnssnjVts3zudd98Zr0mXTIscDBlBdtrksq5JgtbGxKlSKx+TRzUVErYDZs8GJDQfEPKGAu29W1tusVIvCXYqThYdJHSqZHbF4OR2dKpMUvYHo35LaTsyqh0mYuNJpFnobi+SYlgB+dCEHvWQxqq+Ciq5c7D31x14okYJ1HikUj0GocAoyDEQtM8ow+l6YsH7GDCp7ZB0jEpGxjQy7ayORCDCWVJRrSabYuwTjEDSvZO9zMy0ZQI5lVYDux1LdLuf2ag==
    client_secret: AgBppd3FcZdJPr8SgK3nPJmy2WbqhhVw/SnfZuRmvhBxwkJ7TGsu6d/pObLqUBjEpmHUjwTXLI/Gro/0CeGyiNpsyTGaWTlMbPy3I3EXL37hPM1ThwUClvZiIUUveMXzfStGe51p/T4nvT1qRUBTAfQXWPDTaAnQiyaG8nraYn4Rxbcu5K84oyOa0oR/4FNRxd9dNL4rkvgjWwS3CwBa3aZ8L7RJrFU9TIjByPhkYHHAbYyY5tnRK/JfHcPOCTlVTuvrKmBaOGRBytRlNPbqpLoHarWMyD2AppSWmO7dIvmo2FqQ/tp/MiWJvvmukQNtL18tWpQeBAtWyP4ZkHxgwIqHdQw2Cb0QycRejjBvqyYAOHIYZnbqvZBLNw6d24DtDL8prNz+42AbDVL5Wac9rE/K2qvNRIWx/pv+n61H57Pl/yBbyrTeONELrjIFGQnUWHQpVnDG/Ew0RdMBm6aumT6mp8OfYZg3y0iGwlElPSgFSHCL8xH09eHVAgks/ar1bonp0SctYWzi+odJKtNk3sghjHedZJSl75gI8HY7RowF+xHD4fLuX90bNiLVAxRpHaVmNJ17PTzlu+0x2Bs43twTCH/ilcqbU7XjaTH9fuCtqqxT28NSLGCc1YB5xtkEsW7YFdRai6grubqrIX0u44vmHjRrCeu6VenEn8u1Eg5M447n4RQgfFPe5dLL5gzuaI+lICEv9v+CWY0xsZ4hyYQj8D7q4eWklsw0fBL9x4p0L362BiVWBoJFaQE7IMTf3rSZtHER4iWqi6C90TM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
