---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCtE4YaRO95UFPwObl7k2knoQa7rXH7CDgrBEn3jfZSSJ/A6c2XTVaifkvcq/vPmLKUBqWn1L5T10U3/hThjGInqDGtkWfXu/vpV5i+y1LQhdhXNrPAWciXFY9jnmbpRssSxoYKhgFPYvsyPNTlBKuoOY4ZZneVCEjf0okoNP7bkl6HQfKmN5YZVNTjtteLWx2fcU9CRn4w/YDVvcaNsKk16blGaHmzWCLeFW5jhMCkT8rwlNcab2iregDroPZDSRSyo+TzSj+ClpxjD7gLKMSxgSlK5PZZkhSJhilboXmq6z+Stw0OTjG9PiiCIeVJfsfDwPIXEuGis/9KTTrNubUocXWJXM/456PM2uK+yOXmjEc0oUTQFkxI+qwtZQfBJv3z4M8vZgUzsswAmk37rIHI85S3vtSGcqrj7zXd+Xxcueq5qyoYwn/b28vn5Ds4HAc1hyjRses5LaZA/Fydq3dbJKN83iqeGvhl/Tj6xE1DC84NK99mWUxyBUlGIhH6DjiM6wdfCuirMMFRLsYq5NA3NdqSfd+4IiwgPNngjoAqLtV1zIQYELLNIJjdFueNtsOFNXfPjJOi7lCqurtti0/5dkWN1V3goH7N7VAvzIqXTq1XiMnfTeaRimQsrxE+EF39KRUhwewWa0xXOfjK5YvpLOEykaCWiN2qTqT0h9WS4s1mxc6YElpaHs23wz8LdUHGyQejolKEI7kUXk4RBdvS9g==
    client_secret: AgCiOWuUvirtwPykmp47sjqJ5qRB7MfwrmQ6fXtIF8Zy4CW0H1UNVTZJnxXjarg02/lkqgA7T4fXU8d1w+42qaYYFzIF5qZ6MSId5xDYdMllI3ZqVffUmO1bxaMTA73xXBVKFeLobfZiV+HWnd7dTOopfQ8VNc1qKKCpUvOYsGbfsGiOA3jVf7VpkOGY9+P4+hOgG/dHSQmalS4v73HC7XcE9d6KDlweZZHarbcQc7q1rtmfPn5eKFIExv+DKt/9f5DSvlkZ8wka/BzGzwWmAzW8yvkSuP5eIbE0BXgof/bQUq+Rq3Dj7c7UAqYFejnSblns35cRqdQr7oU0eF+J1+W/cy56kCrpXwq+HkNkmcS31ouArsxAdon0CGbnpK+EjUmUrqphqoXB1V7kI+ZVjjndWNd6h75xr2ARVh7anQl/M01S1S/5wuygE0R93NyRHTTmtcruKDyfsIkXMtN8S9HwfulS68WUr/PEgG++pGD2SNuYMmfMrqEDG+XRNzVmkwU5k3PyhvRikiTSjdw4JnuhWgOl+vBbw0Ok8eHc1jWzA8VT5cOpqgVRcyxwlZInQhfaEPGiXGghc9th5LjTXVPDRpX2EOyvVayXU68hgd68endnIwcZI973GlhJpQfrYwWFdOZfVSjk+N12b/DZKZQum0XV3upM+xAevWnnJgcqzBNb99FAmNRPk1RAOMLY9kqKU9USfqgytFzIJsMKlwkTM5dC3fBAZhdAzJ5m6X/MWsnvvG5+fngfB8yP/rpMjZu4mf7OFnb13HmHUtJQ61Kl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
