apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: operator-oauth
spec:
  encryptedData:
    client_id: AgBqoP2CuJPRvM9meCYlrcd0L71mB6aJ3F2pA7d1/hO6CDfsNeUcHGDKfCl6Dtp01gTNpTGrft/On+iRy3BsIqMGqRycgLprtS9IZt/ld83UtkV+Ixtns/8UtCZ+ypCmaqE4ix+oI7jtxUkMCCXhmXruuzL3fobvkeXzw+lcxF8sSK/r93xZ/YE7wqSVCDBssx81FZtcaGA67IrzoOoi+YrwjC3ggMcdho0dqxQ1IWjvhg08cTqBXNhDPbB4ewR0nVnVcpo0V6VvrgGtP7nIxDOvSNG4w925/5KTCUALfvgM7EGu0oZoZPTGlEnQdUsLmvj4IPoAamUfSY2DQ+XSosAaUaVYzEMEu+otjGoVjj3Kqcje7oOfx44NjnZUBtLWXVcOiHQ/FEBwF4JbYsJOCAhsv6tYx87+6QAlPf35cGtCOjCImGeaKBQ569VA9IiDqx1vZ3IEIYkZrsDbg3xl2+RCvM2IcLY9PZI02LGhSmq/z6O5VEX8GIe3EXi2UEKLH+wZ4zsl4mnhGGLN1N8LaMpie0nLYW2cMUgJpRA3206Scxi5Jx4K12rmfSy6nOFUGnUTqL+5NaI4CpJK8ftgdB/wtd4EGZ0FhUOjxl+XtDXsbao19p95178wRQaa9xjgOj0asmXANt30rqglLFnjlAlgnXxiJE7SVRIyYkkJLLm8XRReIV0K7yvcakn9eIds+TcA4WtWFRpdY7fFEZk=
    client_secret: AgBAyMCNAcvAO7UE4652eSGjLOPTBhBnKYQQunKm72uNgwdrKTHfIUt+Fluivcz6ezmYjFrUvmF86qdo2aJUNfqKKdazfUW5fpEJg8bvPqWaQu5GjJu3AQ7U1R2Bmum8T+DP2JM/iTdnS3StkZEE3DOERc6uYNli+Uy9ujyYzcIrA8HSgGoZzrQEcI9FleOnfGZIqJMhLMaCD50Iu4KwD8bRuQk3sp4n4C5p/E6Ud2COI8Pcd3GZl+Y4JM+LTEvP35ekLoO5M4ULNjLn6730HpbvuoolLI5zG0p0UN6LlpA54qBaQUXp4chiKR1YyhaxYa8irGtGRkuQzwWOPJsSegirT9M6yvy9tVxeUCV6Svsw92Jfm7CsXbGei7qOF4zh79cHQ1o/aTJchlp29TpF+hUP+G6LVuQumchJfhSwdxN5wqQwRXaoto+YtBxSZGRMA/WHlYgTczzMs342z5yViS8+fppQeaLiIjP7xFJBoRyVQEjAXBttJv0WtPlDYQhV1qx7DQJDF8FFkP8yEqY4CvXvV3TuKYdHRSuYzYzZq/pTyjr75RDAZP0C5rfwfJlm7qQDywrdavl1a2f5TRHBAvuGYDCv1kQdC1yBKMk5GiwWcLP9WYFTPbe3szVDhV+6pBpNoVp+CgLzomO4jUKv2G31YGh6TxSNPuojfj1cUvdI1t4d4+Dc24YxxWn/DZRXaQty5lSyrNf519kRAUvFTVJt/FS8F1QatuTAa905oMb9TCB+yoYhW+pGh2+ctvTW9DdMOiX0oZC4Fyd2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: operator-oauth
---
