---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBsHgOrwdJMUB4EVtqm0pdxJAUNeQUAlY/REDDTP8JawSx2Vt9vRKkpJQVbzxTglo2nmSBT0LZKizcxPlO6qKBzfecOW3HIxcDhZ97X61brMQ9xB2f/AVp1XBxUYClUsEutEcv+BPwZ6/H7pSemkTgRixfaEr1Sxbynk4w9f0QSvGmbCEvwmAudkRMOJlq6NA0qP1QRu8YmARMtzpppCu2dWkvqu008AvW/0VEcG2iBbx6rpB8yQPfX9U5/OnkUL4dTVTaKqCcRXEg6gYlJjeDG6dEsn5A8MCtebZ3VhUGiKl10hczP29/W/FwSJNF3lwma81uceh/5QR41bEyweHI/4Ps/TogF8CEG06d3dx5OoGl83nreCGUhLwmz8QE+bIr8XgSNfOGj2PPALEfywaKi/ls0/DpMTRLOqB4Ne9vQ5hWTHuPtMp6+3k9ljzvoQN449g7Q8r+uGMlcHdZ/P0uyt9xc9jW3zrPOxnrGTzsI6vxPQeHdadAtQ9ZOUB/vcyFXc/ayOI8wVciMg5RtRlF6P+uQzUjK9itNZb2adwuT9tBqyxHJulGf4x4KVX22Zyau3xvH18fCH7YCbFhIK7O53YtBtTzN6emuP9w1K+cJADAMN+h/cZ4wcFSNX3Mmy+w2OyGRH6Daf0KzW4+xt9kzBBjEuwvEPvVrBNkAbLIXzuftoSbSXU1i8Y1vXsImgIRl+Grurq7nBq8M0aidfRlyVQ==
    client_secret: AgCXC/TJXlD0F+iJLIT0JbXhJVnRZI8th2aEC7Uf9s/b0atRRMkSufrHkmdlxVUzMHJ9Gc8xjw4k4m9Llx06mIAM7xkepBnRFJPYnuuItzL/xRMX3oaN6Pd6959jMe0yJIziAiaeJ9HK7ZDrVqZwZbUdKDjhQJlUy7gZ/wfMYwZiqfhRbxnRNY9cVcbG3Ufnt6WnWsfZ9OJ69dUSEOH7TRKvXA61OtYy62vP2bQ51pWRU1JVpB2pT7P6HKMaY2J9sf8qcimfcl6n0Ruz+OHhHGFpa/CWAXhOMUbm0ARwvBh0iGIGpoDntl/AqeLvACojcfQhqgWlBejpqkPDko7ilAvHr3cLTtq4BZuia8CGWVCvkce1bpxNtRKs7pfIehpDGZeTQP7/KLIxHJH1h3DI4UM9HsyX32VPqNvsDYEOwjvPwiPsLcEf+2bui02imCnHGTExyG0IzH9/xXUWEycNQyoZpIt2inX6GTmYO2WuUgAtnJoywZA0kb2pGpW4plUrzPhIGmFbzc8y+PUIW0l2j2hblhLtOv5ghoLx0juOqQkaOmpthdrT4boUw/S8FwYj7mzjjDgCcg1ph2mSi4Dls7xGww+ND/EMcTN8WqLxbyYtHpL7j3/m0vr9i/zTlvX85Fm3mQuTqdEhS39jjzYv/WKMOMLIqrmHf2cycX+DLDzKEs64robSM+wLJZr0IOrE5ztTcsCTDQ/vEwUM/rJER2OXUJItcZlfSrx17p+FEQcHOiMddM6caSmYP//02h5vc7KPJFyLj9Y+q5znk/3V
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
