apiVersion: v1
kind: PersistentVolume
metadata:
  name: foodiepv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/labfstmp"
