apiVersion: v2
name: metallb-hailmary
type: application
version: 0.0.1
sources:
  - https://github.com/metallb/metallb
dependencies:
  - name: metallb
    version: 0.13.12
    repository: "https://metallb.github.io/metallb"
