apiVersion: v1
kind: Pod
metadata:
  name: basicpod
  labels:
    type: webserver
spec:
  volumes:                            #<-- Add three lines, same depth as containers
    - name: weblog-pv-storage
      persistentVolumeClaim:
        claimName: weblog-pv-claim
    - name: log-config
      configMap:
        name: fluentd-configfun
  containers:
  - name: webcont
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:                     #<-- Add three lines, same depth as ports
      - mountPath: "/var/log/nginx/"
        name: weblog-pv-storage       # Must match volume name above
  - name: fdlogger
    image: fluentd
    env:
    - name: FLUENTD_OPT
      value: -c /etc/fluentd-config/fluent.conf
    volumeMounts:                     #<-- Add three lines, same depth as image:
      - mountPath: "/var/log"
        name: weblog-pv-storage       # Must match volume name above
      - name: log-config
        mountPath: "etc/fluentd-config"
