apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configfun
  namespace: kube-labs
data: 
  fluent.conf: |
    <source>
      @type tail
      format none
      path /var/log/access.log
      tag count.format1
    </source>

    <match *.**>
      @type stdout
      id stdout_output
    </match>
