apiVersion: v1
kind: Service
metadata:
  name: music-assistant-conductor
spec:
  type: LoadBalancer
  selector:
    app: music-assistant
  ports:
  - name: music-assistant-port
    protocol: TCP
    port: 8095
  - name: streamserver
    port: 8097
    protocol: TCP
  - name: streamport
    port: 8098
    protocol: TCP
