apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: music-assistant
  name: music-assistant-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
