apiVersion: apps/v1
kind: Deployment
metadata:
  name: cumberbuns-lubelogger
  labels:
    app: lubelogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubelogger
  template:
    metadata:
      name: lubelogger
      labels:
        app: lubelogger
    spec:
      volumes:
        - name: lubebottle
          persistentVolumeClaim:
            claimName: lubebottle-pvc
      containers:
        - name: lube-benedict
          image: ghcr.io/hargata/lubelogger:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: lubebottle
              mountPath: /config
              subPath: config
            - name: lubebottle
              mountPath: /data
              subPath: data
            - name: lubebottle
              mountPath: /translations
              subPath: wwwroot/translations
            - name: lubebottle
              mountPath: /documents
              subPath: wwwroot/documents
            - name: lubebottle
              mountPath: /images
              subPath: wwwroot/images
            - name: lubebottle
              mountPath: /temp
              subPath: wwwroot/temp
            - name: lubebottle
              mountPath: /log
              subPath: log
            - name: lubebottle
              mountPath: /keys
              subPath: root/.aspnet/DataProtection-Keys
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubebottle-pvc
  namespace: lube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
