apiVersion: v1
kind: Service
metadata:
  name: cumberbuns
  namespace: lube
  annotations:
    tailscale.com/hostname: cumberbuns
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: lubelogger
