apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jarviscraft
  namespace: jarvis
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - jarviscraft
  rules:
  - host: jarviscraft
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minecraft-minecraft
            port:
              number: 25565
