apiVersion: v1
kind: Service
metadata:
  name: jarviscraft
  namespace: jarvis
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: minecraft
  selector:
    app: minecraft-minecraft
