apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: stark-tower
  annotations:
    tailscale.com/hostname: friday
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud-friday
    app.kubernetes.io/name: nextcloud
