apiVersion: v1
kind: Service
metadata:
  name: friday
  namespace: stark-tower
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud-friday
    app.kubernetes.io/name: nextcloud
