apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: nextcloud-friday
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud-friday
    app.kubernetes.io/component: app
    tailscale.com/proxy-class: "irish-eyes"
spec:
  ingressClassName: tailscale
  rules:
    - host: friday
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: nextcloud-friday
                port:
                  number: 8080
  tls:
    - hosts:
      - friday
