apiVersion: v1
kind: Service
metadata:
  name: pierce
  annotations:
    tailscale.com/hostname: pierce
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: web-console
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: director-pierce
