apiVersion: v1
kind: Service
metadata:
  name: pierce-conductor
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: director-pierce
  ports:
    - port: 5000
      name: rstp
    - port: 1935
      name: rtmp
    - port: 8554
      name: noidea
