apiVersion: v1
kind: Service
metadata:
  name: pierce
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: web-console
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: director-pierce-frigate
