apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: frigate-rstp-credentials
spec:
  encryptedData:
    FRIGATE_RSTP_USERNAME: AgAqtzZKnAFab/Or2rSdU+oVGLxx38cktqWb3aTTiDWGVMyxC7OOhmHwYdAkTZ29UXiCD+ZYb45jrekA65SqVQWXSxczC6Dxxg8p+IIj/czIaLmEKQ+AAn1yZPe8GFD0jM8jSudAlji8B+fPxzri3sUBYWTMphCfwMtZyBizEs2MPVI5REDN6XJ2oygFadSYy54eHQMWr2l0bGhB0rrQs39FogheWK2SiKhq2q7hY4V0aDIpn5bopHUv1obypcsLtRlw0b+GTU/ZGgQ0GBbDNVZc/JbUtW36RsgAhIXbv0lDjz3TgoF3ipDj81QD3s3Z+L84pPaN7hkdo3HGwDST70hHYu2ACBHv6DGOUPggEfykRVfwSMM+Qf2Bsh7gwI9L2Ol0QwRLTUEewmWmQB0NaARlNY2ciOG13DGGo2Gspfa1EXQ6OSwB0QaGMCqSKRPTXxScPjSi0C/+YzXt/tRDxEqJPaUyMQF/i01qh2Pq5gCO6T1zQ2QFjwc6aJvvxV74uJ9nPRV3P1chQEP5V1IQTXvxiVlgExcmiv4Z4aNPk5hbe4zMk9VTSpV/MbROv3LWV+H7pdftO2vqCM1FezPoAuL0s3EJGgKLUojBC9J4cuArZ9nwfM2Jpphpm5+6DCT1WGdTIs8xLVwZKx0el6hLK+vaoGh0EykrX1kflQNikOEwVwQiTEp8llqwbcfk8R3uHm5J2rVFfA==
    FRIGATE_RTSP_PASSWORD: AgAkIIebet8nwcoVNpbptOUqURXaDJuls0FpHSBo0DFlOnfmyHkz9/+FzPIZw/RgjgX0xgSACiCBb61Go7IL54AAWcFRmHEzMMKaQmGS7qJRITyZVL6TQ6f0ChzFP1TxXgpyQJ3AWlAySbqPOsi1WRclQuO1LERbIx2vP8lp1g7O4mhlekocwR0DwxX/GgswydqSZhQWMoh6C8PBlkPmsdKumpEmtTWpEarZQXBFx5PYsgzhXV/VFHhyL7UhgXbvYsB1SNZwPwpzgQaJvJfy6nFcXWKpvvsCs+dsqVb7VQaU7FUuFBfh5cYUp9p0sRMudwngeKS2p5O1wNSYKeYumN+dmPrmV2iSPn4PrRIMmDQBXWPP8VCHikt8e+zeWpE52XSTbkmWu9Zyya8a/lSFRNYfydDMFxt8jIcr/jMqoifycAS417w10AmKNim/gzXbEK063pZtoUamn4kkA/EEmkI+Z6jenw5tB3LNozyNwPUjfivgiY/JzDBspHuMDlfyRw5EunvUtlkTRyzX75E2GhlDrakqY1/y59NnJnTGgDkFwX2mwb74aK7HVaU1hkcr1Z5m2UruwlCqgnQD2OU4NOgAEM7DkiEi51Vskcc6Z4oNVUCaaCurg68m9si66mDFqMqp7taq7mmPLeRtHgt4aUqOXK+4b5ZuInf8gDWzg9pfvKMV2OUdgWaw4VDgyxSwIrmbI1Yffp7yVAI5oJ6zcfPNjJaBorIVmrXuUfcP
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: frigate-rstp-credentials
---
