apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre
  annotations: {}
spec:
  rules:
    - host: mitchwrap.maximstroud.de
      http:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: alchemist
              port:
                number: 80
  tls:
    - hosts:
        - mitchwrap.maximstroud.de
      secretName: maximstroud.de-cert

