apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-funnel
  annotations:
    tailscale.com/funnel: "true"
spec:
  defaultBackend:
    service:
      name: alchemist
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - calibre-funnel

