apiVersion: v1
kind: PersistentVolume
metadata:
  name: dreykov-pv
spec:
  storageClassName: "nfs"
  capacity:
    storage: 7Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.77
    path: /whatever/minio
    readOnly: false
