apiVersion: v1
kind: Service
metadata:
  name: stirling
  tailscale.com/hostname: stirling
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: stirling-pdf
  ports:
  - name: http
    port: 443
    targetPort: 8080
