apiVersion: v1
kind: PersistentVolume
metadata:
  name: cannonball-dreykov-pv
spec:
  storageClassName: "nfs"
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.77
    path: /whatever/cannonball
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cannonball-pvc
  namespace: wheeler
spec:
  storageClassName: "nfs"
  volumeName: cannonball-dreykov-pv
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
