apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeSelector:
        app: sonoff-zigbee
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:2.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Chicago
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: "ZIGBEE2MQTT_CONFIG_MQTT_SERVER"
              value: "mqtt://mosquitto-service"
            - name: "ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC"
              value: "zigbee2mqtt"
            - name: "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN"
              value: "true"
            - name: "ZIGBEE2MQTT_CONFIG_SERIAL_PORT"
              value: "/dev/ttyACM0"
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /data
            - name: zigbee2mqtt-udev
              mountPath: /run/udev
            - name: ttyacm
              mountPath: /dev/ttyACM0
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyUSB0
