apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: daboys.maximstroud.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alchemist
                port:
                  number: 80
  tls:
    - hosts:
        - daboys.maximstroud.de
      secretName: maximstroud.de-cert