apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pepper
  name: pepper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pepper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pepper
    spec:
      containers:
        - name: pepper-pots
          image: nodered/node-red:4.0.5-22
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP
          volumeMounts:
            - name: nodered-data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 1880
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1880
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 1880
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-data
