apiVersion: v1
kind: Service
metadata:
  name: pepper-pots
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: pepper
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: pepper
  ports:
  - name: http
    port: 80
    targetPort: 1880
