apiVersion: v1
kind: Service
metadata:
  name: romanoff
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
