apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      name: mosquitto
      labels:
        app: mosquitto
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: mqtt-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: mqtt-data-pvc
      containers:
        - name: mosquitto-mqtt
          image: docker.io/eclipse-mosquitto:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
            - name: data
              mountPath: /mosquitto/data
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-config-pvc
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data-pvc
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
