apiVersion: v1
kind: Service
metadata:
  name: mosquitto-conductor
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - name: standard-mqtt-port
    protocol: TCP
    port: 1883
  - name: extra-fun
    protocol: TCP
    port: 9001
