apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
  - name: standard-mqtt-port
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: extra-fun
    protocol: TCP
    port: 9001
    targetPort: 9001
