apiVersion: v1
kind: Pod
metadata:
  name: mynewpod
  labels:
    pickme: anyoldname
spec:
  containers:
  - name: nginx
    image: nginx:latest
    livenessProbe:
      httpGet:
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
        port: 443
      initialDelaySeconds: 5
      periodSeconds: 5
