---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCNaITeltRpSx3XBO6J5w2lq0JqoLfk8tX/oSQhk3wUKifMDCi3Wjw5sfGmIQnPqjYoohFFVXGI9+8NT7wMttlKba9DecPTzhBUxF3qbYilFpZyYx00ZvIzV6ZsDWfxk5M4FVTuOo3WIgjQ+TMy+BxZZ69fmMOgMca+Krnic0Ef4jLvTfnL+xnnDz73num9JZ8RAN4CxN2rZUrYLWgzGyHW6GBehEUuQYB8joRNUvVl+6UDh0Zq2OUW3tCqTFAbtdgFjify6rFVAfh2S5FrRLrhpbBsZpFNKgEuwwhH9uRNqsr1qAYaTXfV34lXhutlk3+mqB/ZhN6Ir1JcyU/JWKmTemYs0UlLMhLDGz+46kTiD66rd6lbLDFt+MwatRlWjnOcOmWBFtDijb7DIqFBPIxZ7QLizRT/NJLj7HjVD+w5o36JA+sWGE7w75816GRtTOUST++hjHMdeD/dSBtw0mcHuFHrwgsHSuYaGyxJ2NSXNwq8b2F5buYVTgFwmu7PoQcL8ftWprOrCPG1bYJvi5E/FNgV5mo6Deb95Uk24aQqenfFljGh+jYeGVpFypbFsILkGja7em5tdYXM6fSV7S2Io0g2bkNSmtGV1/ZAQxWXaiKAje5kdiV+yv98cmQM2qVaYmyi806Xp0+46sW3IwFNFnMA4Uwr7LHV19b7rE8DH8BolUJgWti77JkUvUYzb/1mIAoqPfskY2zPs/mIg2cZTsJBVOWyIJKOo/ROD7y558TNUgKRF+q2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
