apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- base/redis.yaml
- base/postgres.yaml
- base/deployment.yaml
- base/sidekiq.yaml
- base/pvcs.yaml


namespace: maria-hill
