apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- base/redis.yaml
- base/postgres.yaml
- base/dawarich.yaml
- base/sidekiq.yaml
- base/pvcs.yaml
- base/dawarich-sealed-secret.yaml
- base/config.yaml
- base/tracks-svc.yaml


namespace: maria-hill
