apiVersion: v1
kind: Service
metadata:
  name: mike
  annotations:
    tailscale.com/hostname: mike
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: ollama
