---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: project-insight-secret
spec:
  encryptedData:
    PHOTOPRISM_ADMIN_PASSWORD: AgBdxXBBjc7JW8HQxOV696grtB6kKHwB/eD13VQpz0Ht36YZAyugU2SEq05QRDZ+ZE498RaeAnqLfalwBpZK/TqlIuTC7Ihj/cfJ5J142hiT9a5Z/R3Cpt6awnLBw5NhOjRTb57IGzW7X6Vu/OcpiRaXzfkR4rFeknb8T4lYz/7BUDGgbN2a75lMYnqegVFCOQSSOrLXlyNs2/Edo+QMV5it3hcJGTAJmu86c8FsjniYLaYwsrmycegva/jrbPpieLz8pPReF7PfQ1iBG46n9kegHbPRM0EOwV7BGaZ+XVGO10BFtFu/HUpe0BE3PVS5XO47IuQoujiIlzHkGE7nSS9lW9iwWY5qJS5degmKsEH6h0ureODA1qNz6bNxd3ptN4Z+DIuea631KcpzNFq3yUlmHpSyBj6MK4n7A9PUtlV86WTEgI1XvBOk3WMcnsXPcNqKAMwzjgvFi/+tXnXiM4KVN+v1sqRXSQQiO5h1t+NvpDRnwhfixWQEvnfWWr0hxgu6YURAQce1a0Eoxr9z2lUgm6CFkc1kI1XKG63cHK78IQe95G60D+xN+8G+0cucp2E+bPD+TtE1va98VqCq4gMmpbdWuJ2EeKJmmBoergKqZmBMKMOxhktdu8mJC5vrLZGk3Z/QkCL+/gNkmKL9WlHB2iOUKIwccf22MKjmMJKfz9hptrqpbFdG3opEp5jM0Jp8V+Xr+K6tbPpvqFvMAuU43/9gKsetXb33i0Ox
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: project-insight-secret
