apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: zigbee2mqtt-config-secret
  namespace: maria-hill
spec:
  encryptedData:
    secret.yaml: AgCInKSNA+eaQV+m2FqQkh9v2O0j4ylFQZzQ4DnBDwgF/7mxnNdq/CFBQmKjpg9i0dsqsE4fVX/G7+9zgR5kYdbNvJyVf2+AzKRvzFn/Fc/EjmIjgb3vi7w6Gta2hs91YJDIkTVLuE1dq9bwEi7dk5C98ZjaUdYjIeYLRFQ0Cr2vPd6Lf0uMnWUEQzEX8imcLqpjmlTHF/FLPIGTuAbCE42svC55B75o/VBz1R1Y5ByUtX9fUbTlsjXV9e9S5tK5dVUxO1n4zIwY2z9yRDCxXShqLrr6cXOjUYksuDAgC6YgOcObEJt3RTddmb5yKNRo7yzaw06b1RKZajp4xdJLY4IIEKDQSXE39t/yP23Y+hMRsaLQYU7cApVgap+f2C4ojrnDg2QkcL1+c9BDtWR25tJxlPgRJM2D6DvOI0k6xV3CUirbb0qGqcBMAXoEgzPDoBW2rI/IGVCEu7n0mpKDwUZlLeTumUImLlBTahF7k224r65J8WwjO0knFZVhGTLM+29ztukx2BgBUz2+dRQnR/kwS9qb8bRtn+JKlyzCBVC6On+HmAiXzq1mSFVCOe3g41QUCmrnkvZZXD9YwciDrzvVECikH72eBBdHR0T0qKf+MHv81hCS3U4uu+6y78yEzWorpQ5MxYTf91GDoX9xNJmCGs2RnymGLSlKs6+dUPZQbP4ORIm+QnaSo8FVBExTYRNK/L4Q28YXjj+B1cahUbrtw5dJHbxU71NMDfZ3F8B7f5HLqbbYXS3QDTnU+/31KWCF4zO3md/3QApq4PYj/7jYYGRuV/FNXE52hRingisTpYb7MjGn2nk85kamypW1mO6ehxyk4VI20Pm7OK7w6P/vE7VBjzsLSdd6cV+4qmTPdh8xSlKXoWmuDT0CmgiYuDZCWwQVcz+g
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: zigbee2mqtt
      name: zigbee2mqtt-config-secret
      namespace: maria-hill
---
