vrising-server:
  image: sknnr/vrising-dedicated-server
  imageTag: latest
  serviceType: LoadBalancer
  resources:
    requests:
      memory: 16G
      cpu: 4.0
  volumes:
    dataPVC:
      size: 50Gi
    storageClassName: ""
  env:
    serverName: 'Ravens Morrow'
    serverPassword:
      secretKeyRef:
        name: vrising-server-secret
        key: server-password
    gamePort: 27015
    queryPort: 27016
    description: 'Ravens Morrow'
    bindAddress: 0.0.0.0
    hideIpAddress: true
    lowerFPSWhenEmpty: true
    secure: true
    eosList: true
    steamList: true
    gamePreset: ""
    difficulty: ""
    saveName: "pikodegallo"
