apiVersion: v1
kind: Service
metadata:
  name: longhorn-console
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: longhorn
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: longhorn-ui
  ports:
  - name: http
    port: 80
    targetPort: http
