apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maximstroud.de-cert
  namespace: eternal-library
spec:
  dnsNames:
    - "*.maximstroud.de"
  secretName: maximstroud.de-cert
  issuerRef:
    name: letsencrypt-cloudflare-issuer
    kind: ClusterIssuer
