apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCtl/EdhF5CYF4apLKkIqUuCXqPbi1q9HE7KbDkkBlSNC7xVkE+sj9ow/dX6rDmv8172sFOcMGp7BSt5vDjxjY5sYYKZE4Zt1cehMH6oQce70iQ/vmMtfp/H8IQ+oBHD1B1KfywG7lFWNTn0VItm7/coa3t2UF47IN4CZbQk8b4CwJ5Iwgw7LB/sgfkKCVu2fDjSE7WgVLsI6whWh6zgNBRpiLP80vVg7JtiIenokG64xipfECDrv4JsvQZ/VqZF/XXt61feq92L904Zur3wGYgzJYokM70dJhDIladRxxZ0XJCGi1JeJriZtNxHG/zm1Xzv6+MXhg+MzbxBn70kUhBeyExLHzih/c35XjpzgAq3d+gqjxHOMuXzJola6U0+RsUItCvGZjyGBgXt1COfEf9SF94WuYDdTzs8lIGuLGkTlTh1Mdgn6p5aoITGNrH6norSicQgTagpoFTTAC8uSI4EOm/zVsjeElsDRUGtBGUt2qE5ypqpfk8iopsc+F/08vBKqnEP5W6h7yzACqwWrqh/t/vlua3cnHeKjrw0hOOidC3tiEUnMe7mBDEiocrO/x7SVGbLPJDnw60nDwKtqg6k8p1kvcZ2f4CODqwzUdR4nZBlaOCZzz59EgxOBD2JYguvNs94nIbNGAmaW7GCFa75TAqEORzDKrOWwNqhW61Ko/h9B5SlWz+ec6hoZZyIKmLGWzkaUR/WEPa+v7seqz1A4XY5Zy6FuPuSCL/OKYReYkdynB+q2Kd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
---
