apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust
  labels:
    app: adventure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventure
  template:
    metadata:
      name: adventure
      labels:
        app: adventure
    spec:
      volumes:
        - name: adventure-journal
          persistentVolumeClaim:
            claimName: adventure-journal-pvc
        - name: adventure-journal-db
          persistentVolumeClaim:
            claimName: adventure-journal-db-pvc
      containers:
        - name: adventure-frontend
          image: ghcr.io/seanmorley15/adventurelog-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PUBLIC_SERVER_URL
              value: adventure-backend
              
        - name: adventure-db
          image: postgis/postgis:15-3.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: adventure-journal-db
              mountPath: /var/lib/postgresql/data/pgdata
          env:
            - name: POSTGRES_DB
              value: database
            - name: POSTGRES_USER
              value: adventure
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: adventurelog-secret
                  key: adventure-postgres-password

        - name: adventure-backend
          image: ghcr.io/seanmorley15/adventurelog-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: adventure-journal
              mountPath: /code/media
          env:
            - name: PGHOST
              value: adventure-db
            - name: PGDATABASE
              value: database
            - name: PGUSER
              value: adventure
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: adventurelog-secret
                  key: adventure-postgres-password
            - name: PUBLIC_URL
              value: adventure-backend
            - name: FRONTEND_URL
              value: https://wanderlust.kingfisher-halfmoon.ts.net
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventure-journal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventure-journal-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: adventure-db
spec:
  selector:
    app: adventure
    name: adventure-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: adventure-backend
spec:
  selector:
    app: adventure
    name: adventure-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
