apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust
  labels:
    app: adventure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventure
  template:
    metadata:
      name: adventure
      labels:
        app: adventure
    spec:
      volumes:
        - name: adventure-journal
          persistentVolumeClaim:
            claimName: adventure-journal-pvc
        - name: adventure-journal-db
          persistentVolumeClaim:
            claimName: adventure-journal-db-pvc
      containers:
        - name: adventure-frontend
          image: ghcr.io/seanmorley15/adventurelog-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PUBLIC_SERVER_URL
              value: http://server:8000
            - name: ORIGIN
              value: http://wanderlust
              
        - name: adventure-db
          image: postgis/postgis:15-3.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: adventure-journal-db
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata/subdir
            - name: POSTGRES_USER
              value: adventure
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: adventurelog-secret
                  key: adventure-postgres-password

        - name: adventure-backend
          image: ghcr.io/seanmorley15/adventurelog-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8000
          volumeMounts:
            - name: adventure-journal
              mountPath: /code/media
          env:
            - name: PGHOST
              value: "localhost"
            - name: PGDATABASE
              value: "database"
            - name: PGUSER
              value: "adventure"
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: adventurelog-secret
                  key: adventure-postgres-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: adventurelog-secret
                  key: adventure-postgres-password
            - name: PUBLIC_URL
              value: "http://server:8000" # Match the outward port, used for the creation of image urls
            - name: FRONTEND_URL
              value: "http://wanderlust"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://wanderlust.kingfisher-halfmoon.ts.net, http://localhost:3000, http://wanderlust, http://127.0.0.1:3000, http://127.0.0.1:9123"
            - name: DJANGO_ADMIN_USERNAME
              value: "admin"
            - name: DJANGO_ADMIN_PASSWORD
              value: "admin"
            - name: DJANGO_ADMIN_EMAIL
              value: "admin@example.com"
            - name: DEBUG
              value: "True"
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventure-journal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventure-journal-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: adventure-db
spec:
  selector:
    app: adventure
    name: adventure-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: adventure
    name: adventure-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80