apiVersion: v1
kind: Service
metadata:
  name: wanderback
  namespace: project-insight
  annotations:
    tailscale.com/hostname: wanderback
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: adventure