apiVersion: v2
name: home-assistant
type: application
version: 0.0.1
sources:
  - https://artifacthub.io/packages/helm/k8s-at-home/home-assistant
dependencies:
  - name: home-assistant
    version: 13.4.2
    repository: "https://k8s-at-home.com/charts/"
