apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooking
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      name: mealie
      labels:
        app: mealie
    spec:
      volumes:
        - name: recipe-book
          persistentVolumeClaim:
            claimName: recipe-book-pvc
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.7.0 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: recipe-book
              mountPath: /app/data
          env:
            - name: DB_ENGINE
              value: sqlite
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-book-pvc
  namespace: natasha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
