apiVersion: v1
kind: Service
metadata:
  name: yelena
  namespace: natasha
  annotations:
    tailscale.com/hostname: yelena
  labels:
    tailscale.com/proxy-class: "irish-eyes"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9925
  selector:
    app: mealie
