---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mealie-secret
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBNTgJto7wiSvIJPumstreN1Kihs9sxhcLFzv+RJfQKl+Q7pyEz4Ht70I0KiyC/RXQRcGbLhX9hy65bUmOVnbmq4GkbOvBNCGBU0zSkrd7ZNNg2JQn6KUyfpAyQe3feZiWczmPLkxIMQQNa/4lAaF0hdehJp7W3AqzuW6p6bvEnvIUZGGCn8TZUpx4kciK2xlZvaZDxppSnYOOof6fALvP9EfHRVVKkaqFI/CAT5+GBiZ1c8BcRj1pDFXaFatPXSLi4nzDWCDVG5z3NWHCwLSxh0sULmbUvSOHS+vbBKXtrWgzMyvc7Mze8FdsmTK2ZwhvjYd7jzqLQGWdHkI+zXwHiwH4MK2LOwD7VK3D87rR1Y9hIS8L3Jd8gdowfDLb1TTnEEwpGe5eA0dLVyv6thQfPnlRs1EDjbsf5/t+bV9D7dlJBHHpNmjZb4e7nnGPMV+UmtnoXLdj2Xpjz6CQMMR/HKRcLOh0WrCZV+cWLJppEUO/HgF4WaRsy43szU5zt8VBgnTsb78e4hOT+GEcZPXXHGKe9H6zadnV5sE45z965GQGs2Xn3mZj6um5nhS5TQivXzS5ltwS6l7X+Z1ReGVPY16xvr+SdTrk0lECd1Bj1Yec0duqHglZcjaeas1tR3xy5LANeU4g0yq579mbGP5U5nI7pZ/Fi117JLZVyMg9Az/shYun9thCzdxRALCODg9A+YbwZafX/AbZ3ra7kDntHk6GaTwAbnpT/
    POSTGRES_USER: AgBEm6YnMJ88AEQoLzoSWwP73koAwnZh8TCycM83QsrcpCrcgNxugka/EIkH76KQhZuhSCj2Yy2Y9rINFkL66X/xKR3tcKWGfwcb8eWkd349tJXZgZIyQUyDelB12Y8uqMLsoM00wfysCFJuh5/pzFuIQXI+k9G/xZ1k/Z5USb2tFJPmhejiYdGTdQ84vpFIheaWEnMJWLWR8h4Elfvy8/5mMfaN/bZQtUiZAnY5F4NCIFMmsrcJRwOTCfYcQwfAzKfEn3MjZ5/xUOfeO5Sy0t//8ziKv5RSWYOp0uRprKnR0ugxbFasV/hRvQUtH+0XCYyxmi+wiCBjkWgWJFdhHJTl+FFWezCLH+O28TprmjQ2fBmO8aDWaTtCFa1/82hYCnBb2VhG2w4lLtm6WXJFcT1S/RwbMusp4Z42wxH0g2fPJPiLeUwq9Q0wEyzEASNWoaoibIG7xMETnO6D/Tj07MneCb9ztfzKR6PZoCNkkjDnS/L9EqTTQkg2sJXaKuUMMSJiB74vsUvl5p56HjHQ7IiHKjurq9MMDDeu3pb6csIuHWZPysGCwgHrN+diVAb4k493MAfgBsv3Q5NkqltFBNeM6GrKtwBtR+wnWWk4i+NET+ssSgdyQz9XtmDbLPo5S2cotES6RVpzt4HPXHMoxBLZGKSRXhUoCpPZUphrBxnMaVFuBaxHzBbDiokrguNWqoV7z4txZRNTCzhPJBWV8kwd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mealie-secret
