apiVersion: apps/v1
kind: Deployment
metadata:
  name: tahiti-phantom-tollbooth
  labels: 
    app: phantom-tollbooth
spec:
  template:
    metadata:
      labels:
        app: phantom-tollbooth
  selector:
    matchLabels:
      app: phantom-tollbooth
  template:
    metadata:
      labels:
        app: phantom-tollbooth
    spec:
      volumes:
        - name: phantom-tollbooth-storage
          persistentVolumeClaim:
            claimName: tahiti-paperless-ngx-consume
      containers:
      - name: tollbooth
        image: garethflowers/ftp-server
        ports:
        - containerPort: 20
          name: ftp0
        - containerPort: 21
          name: ftp1
        - containerPort: 40000
          name: ftp40
        - containerPort: 40001
          name: ftp41
        - containerPort: 40002
          name: ftp42
        - containerPort: 40003
          name: ftp43
        - containerPort: 40004
          name: ftp44
        - containerPort: 40005
          name: ftp45
        - containerPort: 40006
          name: ftp46
        - containerPort: 40007
          name: ftp47
        - containerPort: 40008
          name: ftp48
        - containerPort: 40009
          name: ftp49
        env:
        - name: FTP_PASS
          value: "jarjarbinks"
        - name: FTP_USER
          value: "qigon"
        volumeMounts:
          - mountPath: "/home/qigon"
            name: phantom-tollbooth-storage
---
apiVersion: v1
kind: Service
metadata:
  name: phantom-conductor
spec:
  type: LoadBalancer
  selector:
    app: phantom-tollbooth
  ports:
  - port: 20
    name: ftp0
  - port: 21
    name: ftp1
  - port: 40000
    name: ftp40
  - port: 40001
    name: ftp41
  - port: 40002
    name: ftp42
  - port: 40003
    name: ftp43
  - port: 40004
    name: ftp44
  - port: 40005
    name: ftp45
  - port: 40006
    name: ftp46
  - port: 40007
    name: ftp47
  - port: 40008
    name: ftp48
  - port: 40009
    name: ftp49
