apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tahiti-redis-secret
spec:
  encryptedData:
    tahiti-redis-password: AgAUHHv8mvMJhESrdYXSOlac3FThFxxrmaUlvxOx7D6Dz0lluDKNot8axz+xy7Ylib/gzgiEGZuzJsFJRzQGJ5QE/6JkWb7HXd8eU8f+0+Zf0L5yPnSd0auZ8iRlMpVsUKUT0hp6SU+mUVMTeumL30INCJwwBYorX9W608TcBEKvzDFbYY3aE3/npBYBnrr6Qnzpry945pLj8+aDD5p6PLQMiYcRq0UppuKbqPLKJzcUGIl8iDdu6uyXp+0Lah03mZgKqJbL4JqHyQVrhxA1NOVH7o/57XlkVw1bQolm6hQOuh5R+SIG/9ae/Cf864aSnhKCMRNjTe3twYMLVXmVDUzi1D51Tni7hZuu4sMwFLW6cGVF4VPWW4cQ647BRq5JUwOelsUNgIgrr4q7AXqgtIfi2pZnh9DjCPjEPK70ERJ7Gewhj+QEUXOICD64fDapVoSenMWUY9zSPYnQPcqf5/Cihm7MdwHZGaWoreDBdlOqNxKLehfcW2vlPBQPQmCNQpOjylOdsXYgQWB6JD/+2ormNqO1yK4g1Fmef4rd4L6sYTPMjmd0qEU8/WKixojAJowJnvHKBc6di3XF/ksFDx8CCbe9Ji3X5QyW/Qbmz5jniQBJmVZxUXq4RpgS2cZNrRWiXTYNM9E167UJOQlPn8gz5U2Nui7evaUczjrFvG2WhUeq8KrYrEzWygaRCloga274xD/XbryD7KW6Yab5eOBInEm7sFVyJIHvzz3LrVU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tahiti-redis-secret
---
