apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-project-insight
  namespace: project-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
