apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-sidekiq
spec:
  selector:
    matchLabels:
      app: dawarich-sidekiq
  template:
    metadata:
      labels:
        app: dawarich-sidekiq
    spec:
      containers:
        - name: sidekiq
          image: freikin/dawarich:latest
          command: ["sidekiq-entrypoint.sh"]
          args: ["sidekiq"]
          envFrom:
            - configMapRef:
                name: dawarich-config
            - secretRef:
                name: dawarich-secrets
          volumeMounts:
            - name: public-data
              mountPath: /var/app/public
            - name: watched-data
              mountPath: /var/app/tmp/imports/watched
            - name: storage-data
              mountPath: /var/app/storage
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "bundle exec sidekiqmon processes | grep ${HOSTNAME}"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
          resources:
            limits:
              cpu: "500m"
              memory: "4Gi"
      volumes:
        - name: public-data
          persistentVolumeClaim:
            claimName: dawarich-public-pvc
        - name: watched-data
          persistentVolumeClaim:
            claimName: dawarich-watched-pvc
        - name: storage-data
          persistentVolumeClaim:
            claimName: dawarich-storage-pvc