apiVersion: v1
kind: Service
metadata:
  name: stirling
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: stirling-pdf
  ports:
  - name: stirling-service
    protocol: TCP
    port: 8080
