apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.broccoli: login
