apiVersion: v1
kind: Service
metadata:
  name: alfred-conductor
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: open-webui
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http